### ISSUE TITLE
Broken Team Page on Safari

### ISSUE THREAD

**Issue by the-dagger** [coding-blocks/coding-blocks.github.io#108]
Apparently the team page appears to be broken on safari.
It works fine on other browsers.

<img width="919" alt="screen shot 2017-06-05 at 3 52 26 pm" src="https://cloud.githubusercontent.com/assets/6565270/26780861/4f149c46-4a09-11e7-83ab-8aa772482036.png">

**Comment by anu0012** [comment]
Already mentioned in #96

**Comment by the-dagger** [comment]
Oh, didn't know. 
Thanks.
