### ISSUE TITLE
Design BOSS Logo

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#121]
Prefer CB Color scheme. Logo should be flat & simple.

**Comment by shubhamvashisht** [comment]
I have added a logo i designed here https://drive.google.com/open?id=0B6r_m6bUVO6xNl9OaDFSeG9CWU0 
All requirements are taken under consideration.
1. Flat
2. CB color scheme.
3. Its simple and creative :smile: 
SVG and PNG both added.

**Comment by prateekiiest** [comment]
@prateek27 
I have worked on making the logo keeping the requirements in mind as said by you.

- Flat

- Simple

- CB color scheme
![screenshot 13](https://user-images.githubusercontent.com/16035442/27223572-99cc5f46-52ae-11e7-8c33-11f39d671af5.png)

**Comment by championswimmer** [comment]
At least make the logo related to `coding`, `opensource` or `software` :P

**Comment by prateekiiest** [comment]
@championswimmer 
I am adding some designs here

- **First **
![screenshot 21](https://user-images.githubusercontent.com/16035442/27252981-5ca8dee8-5388-11e7-96ab-4ea0e550184c.png)

- **Second**
![screenshot 23](https://user-images.githubusercontent.com/16035442/27253035-40179bc4-5389-11e7-807f-36282ac61616.png)

- **Third**
![screenshot 24](https://user-images.githubusercontent.com/16035442/27253037-487aa6b2-5389-11e7-8b35-2511f227af81.png)


@championswimmer , how are these?

**Comment by prateekiiest** [comment]
@prateek27 , @championswimmer , pls check these logos.

**Comment by prateek27** [comment]
@prateekiiest First one is looking good, can you provide some more ?

**Comment by prateekiiest** [comment]
Yeah sure. I will be adding some more logos in the meantime. :)

**Comment by ArushiSinghal** [comment]
@prateek27 @championswimmer Please have a look on these icons
![imageedit_23_8686975851](https://user-images.githubusercontent.com/20858804/27493072-0cd263b6-5866-11e7-87f6-f2a394d3deee.jpg)
![imageedit_14_3722584825](https://user-images.githubusercontent.com/20858804/27493074-0e55610c-5866-11e7-8d19-2d907414bd32.jpg)
![imageedit_14_9276705589](https://user-images.githubusercontent.com/20858804/27493079-1398f49e-5866-11e7-98ab-dc2010e57bff.jpg)
![imageedit_11_6377166293](https://user-images.githubusercontent.com/20858804/27493084-1588455c-5866-11e7-9029-4a1e7656bdbd.png)
![imageedit_9_8321715239](https://user-images.githubusercontent.com/20858804/27493087-17c676fe-5866-11e7-87df-27fc232a61a4.png)
![image 2](https://user-images.githubusercontent.com/20858804/27493093-1c7db36a-5866-11e7-9261-0903ddc49480.jpg)
![5](https://user-images.githubusercontent.com/20858804/27493102-24419904-5866-11e7-9dc1-ef4165a1d5b6.png)
![4](https://user-images.githubusercontent.com/20858804/27493106-270c616e-5866-11e7-8f5a-031ecd18d4b8.jpg)
![2](https://user-images.githubusercontent.com/20858804/27493109-28ff1f5c-5866-11e7-9087-53396f80043a.jpg)
![3](https://user-images.githubusercontent.com/20858804/27493116-2c45f60e-5866-11e7-85be-0e156fee6770.png)
![imageedit_26_2251242354](https://user-images.githubusercontent.com/20858804/27493191-7e8f91c2-5866-11e7-8fb7-58d6f8af7f0d.png)

**Comment by prateekiiest** [comment]
@prateek27 
Some more logos coming you way
![screenshot 29](https://user-images.githubusercontent.com/16035442/27495002-e59d8cf0-586d-11e7-8f13-2631e5ce86fa.png)

![Uploading Screenshot (30).png…]()

**Comment by championswimmer** [comment]
@ArushiSinghal logo 11 looks nice.
Can you design it in CB's colors (red fc4f4f and shades of grey)

**Comment by prateekiiest** [comment]
@championswimmer 
@prateek27 
how are the logos?

**Comment by ArushiSinghal** [comment]
@championswimmer @prateek27 here are some shades of logo 11 with colours including white,#fc4f4f and #e6e1dc which are the CB's colors.
![imageedit_67_6268591642](https://user-images.githubusercontent.com/20858804/27507454-6d0d2c66-58ed-11e7-8729-5dc66f25b9a6.png)
![imageedit_48_9979904606](https://user-images.githubusercontent.com/20858804/27507457-6f630134-58ed-11e7-88e1-196504256503.png)
![imageedit_66_5288576450](https://user-images.githubusercontent.com/20858804/27507459-714e2eb0-58ed-11e7-890d-a90adad4d63a.png)
![imageedit_27_6149036347](https://user-images.githubusercontent.com/20858804/27507461-75cac052-58ed-11e7-94e2-d549235f39b8.png)
![imageedit_55_9950735487](https://user-images.githubusercontent.com/20858804/27507462-7839499e-58ed-11e7-92ab-1c2a95e51168.png)
![imageedit_55_99507354871](https://user-images.githubusercontent.com/20858804/27507463-7b567ac0-58ed-11e7-8c24-25f2001f175e.png)
![imageedit_64_9995345484](https://user-images.githubusercontent.com/20858804/27507464-7cfa44d8-58ed-11e7-9f9e-2ec16d73cfa4.gif)

**Comment by prad0** [comment]
![boss_logo](https://user-images.githubusercontent.com/29672940/27507819-3ac67426-58f5-11e7-9438-559baa1b7743.png)

**Comment by prad0** [comment]
2)
![boss_logo2](https://user-images.githubusercontent.com/29672940/27507833-92083634-58f5-11e7-8c13-265d08ea6b58.png)

**Comment by ArushiSinghal** [comment]
@championswimmer  please review.

**Comment by championswimmer** [comment]
number 3 of https://github.com/coding-blocks/coding-blocks.github.io/issues/121#issuecomment-310827831 looks good. You can make a PR to add it to the BOSS side. 

Not part of this bounty (you'll get it when we start using the logo), can you also design a monochrome version (in white outlines maybe.) which can look good when using on a red background or any dark background)

**Comment by ArushiSinghal** [comment]
@championswimmer Yes.

**Comment by prateekiiest** [comment]
@championswimmer 
how are the boss logos which I gave.
Any improvements to be made?
