### ISSUE TITLE
Design a 404 page for website

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#122]
404 page should be creative and interesting like Github's 404 page.

**Comment by gabru-md** [comment]
Sir, Can i add a page?
I am not a student at Coding Blocks though.
But i would like to commit a page for the very issue.
May I?

**Comment by ananay** [comment]
@prateek27 Is this issue still open?

**Comment by prateek27** [comment]
@ananay  Yes. You can work on it. I can compare the designs.

**Comment by ArushiSinghal** [comment]
@prateek27 Please review
a)
![imageedit_2_2331844996](https://user-images.githubusercontent.com/20858804/27622645-fceafd58-5bf5-11e7-848b-1cb2523dbd1b.png)
b)
![imageedit_6_3767478901](https://user-images.githubusercontent.com/20858804/27622646-00690290-5bf6-11e7-8367-cd3fe901f8cb.png)
c)
![imageedit_4_4593279886](https://user-images.githubusercontent.com/20858804/27622647-00ad8b0e-5bf6-11e7-9050-105278f5b21e.png)

**Comment by parimatrix** [comment]
Is the issue still open. I would like to work on this.

**Comment by parimatrix** [comment]
@prateek27 
I worked on a design. One thing that I would like to say is that making a heavy page with resources is not an optimum situation for a page which is of no use to the user. Please review. Any feedback would be great.


![screenshot_404](https://user-images.githubusercontent.com/25114873/27760317-1a9f6834-5e62-11e7-9d38-6787533db688.png)

**Comment by ArushiSinghal** [comment]
@prateek27  please review.

**Comment by hereisnaman** [comment]
@ArushiSinghal nice work. f) one looks good to me. 👍

**Comment by ananay** [comment]
@ArushiSinghal they look great but I guess they won't be taking templates. The first one is copyrighted, infact.

![image](https://user-images.githubusercontent.com/5569219/27804267-979a9ad0-604b-11e7-8dd8-5539f6b14428.png)

**Comment by ArushiSinghal** [comment]
@ananay we can use them, but for the first one if we want to use that then we have to just keep the backlink as it.

**Comment by parimatrix** [comment]
@ArushiSinghal 
They look nice. But are they designed completely using HTML CSS or some other resources too or right now they are designs and not webpages

**Comment by ArushiSinghal** [comment]
@parimatrix yes, they are designed using HTML, CSS and javascript.
And they are not the final designs, some editing is required in them.

**Comment by ananay** [comment]
@championswimmer  @prateek27 Here's my 404 Page. Fully Responsive. Created from scratch to match the color scheme and style of coding blocks.

https://ananay.me/404cb/

**Comment by ArushiSinghal** [comment]
@ananay Nice design but I think the page is not responsive.
when I am resizing the page, the logo is hiding behind.
I attach the screenshots of the page:-
a)
![screenshot from 2017-07-05 14-05-24](https://user-images.githubusercontent.com/20858804/27856356-7fe95d40-618b-11e7-8d13-5543933ef244.png)
b)
![screenshot from 2017-07-05 14-06-45](https://user-images.githubusercontent.com/20858804/27856358-80971322-618b-11e7-8b3c-0da203fc446c.png)
c)
![screenshot from 2017-07-05 14-06-53](https://user-images.githubusercontent.com/20858804/27856364-84b94c90-618b-11e7-98c2-d069d8e1df82.png)

**Comment by ananay** [comment]
@ArushiSinghal Such a ratio of width and height doesn't exist for any device. However, I'll try my best to fix that.

**Comment by ananay** [comment]
@ArushiSinghal such a ratio of device width and device height doesn't exist, so that way of testing responsiveness is incorrect.

**Comment by ananay** [comment]
#150 Here you go @prateek27 ! :D

**Comment by prateek27** [comment]
I have accepted the final design sent by @ananay and bounty has been increased to 500 seeing the creativity involved. Everyone gave nice tries but this one is the best. Keep contributing ! The issue is now closed.
You can also check the animations on the page - https://codingblocks.com/xyz
![404](https://user-images.githubusercontent.com/5269147/28065993-bd3e256e-6658-11e7-9077-db5ba0c08ce6.png)
