### ISSUE TITLE
If redirecting to new web-page then it should open in new tab/page.

### ISSUE THREAD

**Issue by ArushiSinghal** [coding-blocks/coding-blocks.github.io#138]
In this example In "competition" if click on Hacker-blocks It should open in new tab.
![screenshot from 2017-06-26 01-38-41](https://user-images.githubusercontent.com/20858804/27650600-06c4813e-5c53-11e7-9886-221d55ca7b54.png)

**Comment by championswimmer** [comment]
Make all external links target="_blank"

**Comment by ArushiSinghal** [comment]
@championswimmer working.

**Comment by Nshul** [comment]
@championswimmer Please close this issue,if it is resolved
