### ISSUE TITLE
do we require all these font weights

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/coding-blocks.github.io#196]
https://github.com/coding-blocks/coding-blocks.github.io/blob/015c4a934373ddaf0885f3cbcdde8532d9e7131c/src/assets/styles/custom.css#L2

@hereisnaman please check and reduce if possible

**Comment by hereisnaman** [comment]
Lato used by the theme-fire with 300,400,700 being used. 
Nuinto being the body font, normal and bold obviously needed, 500 used at some places.
Raleway being the font for the headings with 300 but others can also be used to customize content.
