### ISSUE TITLE
[SEO] Add JSON-LD schema to course pages

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/coding-blocks.github.io#24]

**Comment by hereisnaman** [comment]
JSON-LD Schema is easier to integrate and manage than microdata. Will be working on it.

**Comment by hereisnaman** [comment]
See [THIS](view-source:https://hereisnaman.github.io/coding-blocks.github.io/courses/launchpad.html) example of how I used JSON-LD markup instead of microdata for review snippets.

**Comment by hereisnaman** [comment]
Resolved here: https://github.com/coding-blocks/coding-blocks.github.io/pull/60
