### ISSUE TITLE
Debranding: Scrub "Pandora" and officially use "Android Course"

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/coding-blocks.github.io#240]
We will be having
 - Android App Development Course 
 - Android Development Live Course

scrub all mentions of "Pandora", we are debranding that name.

**Comment by championswimmer** [comment]
Create pages like this `/courses/classroom/android.html` 
Earlier pandora.html pages can be HTML head redirects (like http://codingblocks.com/boss )

**Comment by hereisnaman** [comment]
Will be creating android-development.html and web-development.html. Also working on using course id rather than course name everywhere, so might take little more time.
