### ISSUE TITLE
Change disqus account

### ISSUE THREAD

**Issue by witty123** [coding-blocks/coding-blocks.github.io#288]
<img width="1434" alt="screen shot 2017-12-05 at 4 18 35 pm" src="https://user-images.githubusercontent.com/7976098/33603311-1a8cba80-d9d8-11e7-935c-eac0672459d5.png">
Current disqus account is linked to championswimmer's disqus account in resources part

**Comment by hereisnaman** [comment]
Have created a discus site coding-blocks.disqus.com with the new account created by Mohd Fahad. 
Updated blog and resources with the new shortname. PRs: https://github.com/coding-blocks/blog.codingblocks.com/pull/38 https://github.com/coding-blocks/resources/pull/43
