### ISSUE TITLE
BUG/ IMPROVEMENT

### ISSUE THREAD

**Issue by academy-codex** [coding-blocks/coding-blocks.github.io#47]
Whenever you open a question on hacker block like for example https://hack.codingblocks.com/practice/p/89

Now if i change URL to some other problem like
https://hack.codingblocks.com/practice/p/100

Then i should get NO PROBLEM FOUND.
 However, the spinner keeps on spinning infinitely in such case.

<img width="960" alt="bug" src="https://cloud.githubusercontent.com/assets/23010145/25301953/64151778-2750-11e7-9078-9f8d4845b71f.PNG">

**Comment by championswimmer** [comment]
Thank you so much for filing this bug, 

Can you please post it on http://github.com/coding-blocks/hacker-blocks as that's the appropriate repository hack.codingblocks.com :)
