### ISSUE TITLE
problems in the hero slider

### ISSUE THREAD

**Issue by adarsh1021** [coding-blocks/coding-blocks.github.io#56]
For issue #29 

## 1. Found stray text
This piece of stray text was found on the homepage. I know this is silly but I am reporting this because this is easily noticeable while loading since it is on the top of the homepage.
![1](https://cloud.githubusercontent.com/assets/22254286/26053151/5deac14e-3985-11e7-88b2-e21cb47f3468.png)
![3](https://cloud.githubusercontent.com/assets/22254286/26053226/aa08e63c-3985-11e7-8750-04f3edd9beb4.png)

## 2. Loading of sliding images
The sliding images are taking a while to load on a standard connection. All the 4 images together are 2.49mb. This is causing the page to look like the below image while loading. ( the 4 slides are displayed one below the other in gray with only text )
![2](https://cloud.githubusercontent.com/assets/22254286/26053047/f5414be0-3984-11e7-9933-165ecbc6c43d.png)

The solution could be to use vector images or to pre-load the 4 images using simple Javascript. Also a small gif loading animation can be displayed while loading these images. So now the user can scroll down and look through the rest of the site while the slides are being loaded.

**Comment by championswimmer** [comment]
Thanks for submitting the issue ! 
Please claim your bounty on https://boss.codingblocks.com 
(In the PR field, insert link of this issue you opened only)
