### ISSUE TITLE
The team section has column issue in Safari Browser

### ISSUE THREAD

**Issue by Srijancse** [coding-blocks/coding-blocks.github.io#59]
<img width="1280" alt="screen shot 2017-05-17 at 5 04 33 pm" src="https://cloud.githubusercontent.com/assets/17395983/26152054/18527d6c-3b23-11e7-801b-22d35bdfd666.png">

Safari browser specific issue. Could be fixed with simple CSS.

**Comment by championswimmer** [comment]
does it still exist anymore ?

**Comment by Srijancse** [comment]
Yes, it does.

**Comment by championswimmer** [comment]
#96 mentions it too. If you want your 20 bounty points for pointing out the issue, you'll get it. Since I already added labels on #96, I am closing this
