### ISSUE TITLE
Design a nice layout for achievers and success stories page.

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#62]
We want to put up photos for achievers (GSOCers, students who have cracked internships and placements )

Expected Design -
There are two parts in the page - A Carosel at the top(4-5 students), followed by a grid layout(50 students)

1) A carousel of success stories( 4-5 cards) in the top of page.
Each success story slider will be a card having student photo, name, college and short paragraph.

2) Grid Layout (40-50) students. Images will be shared by us.

**Comment by Abhi2424shek** [comment]
Can I work on it @prateek27? Please?

**Comment by prateek27** [comment]
Yes Please start working.

**Comment by prateek27** [comment]
Use these sample images for grid layout @Abhi2424shek 

![adobe_ utkarsh_pandey adobe](https://cloud.githubusercontent.com/assets/5269147/26278125/2fb7d20a-3db1-11e7-95b8-ab31e652c93e.jpg)
![akarsh srivastava](https://cloud.githubusercontent.com/assets/5269147/26278124/2fb75e6a-3db1-11e7-90d5-c46a539dd212.jpg)
![amazon_1](https://cloud.githubusercontent.com/assets/5269147/26278126/2fbc7350-3db1-11e7-99f1-081720196a3f.jpg)
![amazon_4](https://cloud.githubusercontent.com/assets/5269147/26278127/2fbccf9e-3db1-11e7-9ca5-53a7cbb40a35.jpg)
![amazon_5](https://cloud.githubusercontent.com/assets/5269147/26278128/2fc18d40-3db1-11e7-85bb-cd7ef1780717.jpg)
![amazon_6](https://cloud.githubusercontent.com/assets/5269147/26278129/2fc41f2e-3db1-11e7-987d-e4648cf991f9.jpg)
![amazon_7](https://cloud.githubusercontent.com/assets/5269147/26278130/30158738-3db1-11e7-917d-4b9d90fae9dd.jpg)
![arshia and pooja](https://cloud.githubusercontent.com/assets/5269147/26278131/30189c16-3db1-11e7-8415-dfd2298e5ded.jpg)

**Comment by Abhi2424shek** [comment]
Working...

**Comment by a2batic** [comment]
I have worked on following design as per requirements.
Please review it @prateek27 
![pr62](https://cloud.githubusercontent.com/assets/12200504/26307497/89ff0780-3f12-11e7-89e0-fe4710369994.png)

**Comment by Abhi2424shek** [comment]
upss, I was working on it a2batic, however since you have made a design prototype, please go on :)

**Comment by a2batic** [comment]
Hey @Abhi2424shek, I asked @prateek27 to work on it on gitter, I think multiple people can work on the design, they can take up the best of both of them

**Comment by hereisnaman** [comment]
@prateek27 done : https://github.com/coding-blocks/coding-blocks.github.io/pull/104

**Comment by prateek27** [comment]
@a2batic @hereisnaman  Accepting both of the designs.
@a2batic I will use your page to show winners of our  Hacker Blocks Monthly Contest, please send PR and claim your bounty.
@hereisnaman is page and complete and will be used for success stories.

200 Bounty points for both :D

**Comment by hereisnaman** [comment]
@a2batic I have used your header image. Saved and did some photoshop. Your work looks really good, hope you dont mind me using the header. :) Thanks.

Thanks @prateek27 .

**Comment by a2batic** [comment]
Thanks @hereisnaman, yes definitely you can use the header, I can send you svg file if you require. Your are really working awesome :).
Thanks @prateek27

**Comment by hereisnaman** [comment]
@a2batic thanks a lot. Well can you just submit a PR and replace it with svg. You will get some bounties too :)

**Comment by hereisnaman** [comment]
@a2batic can you please send the SVG ?
