### ISSUE TITLE
Design a Photo Gallery Page

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#64]
A nice Photo gallery to share event photos and other random photos.

Suggest new features in Photo Gallery - 50 Bounty points extra.

**Comment by hereisnaman** [comment]
Some Suggestions here:

- Event photos grouped together and displayed as albums on the main page. Separate pages for each event.
- Event pages linked in the gallery.
- LightBox (fb style)
  - Love counter (insta style)
  - comments (disqus)
- Social Share buttons
- Event story on subpages(event page), describing about the event and outcomes.

**Comment by hereisnaman** [comment]
Done: https://github.com/coding-blocks/coding-blocks.github.io/pull/80

**Comment by a2batic** [comment]
Some suggestion:
We can dedicate each row for a specific thing. Like one for event, one for courses and etc . It will give a categorised gallery.

**Comment by hereisnaman** [comment]
@a2batic we are already doing the same. we have multiple galleries meant for that purpose only, I have explained in my PR: https://github.com/coding-blocks/coding-blocks.github.io/pull/80

Still thanks for the suggestion.
