### ISSUE TITLE
Suggestion: Photo Gallery

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/coding-blocks.github.io#69]
Some Suggestions here:

- Event photos grouped together and displayed as albums on the main page. Separate pages for each event.
- Event pages linked in the gallery.
- LightBox (follow: [fb style](http://sachinchoolur.github.io/lightGallery/demos/comment-box.html))
  - Love counter (insta style)
  - comments (disqus)
- Social Share buttons
- Event story on subpages(event page), describing about the event and outcomes.

**Comment by prateek27** [comment]
Accepting these suggestions.

**Comment by hereisnaman** [comment]
For now have integrated [this gallery](http://sachinchoolur.github.io/lightGallery/demos/comment-box.html) locally.

Just have to give a proper layout.
