### ISSUE TITLE
Kids and Online Course section needed on home page

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#74]
Highlight the Code4Kids Course on Home Page. Create a small section.

Highlight the Online Course on Home Page. Create a small section.
( Sample Layout attached for reference)

 The Design must be responsive. The text should come below image in case of mobile.

Each section has two parts - Image/ Logo on the left/right.
Content on the opposite side of image.
![layout_changes](https://cloud.githubusercontent.com/assets/5269147/26276523/c37aa578-3d96-11e7-8f91-dc96741ff390.png)

Image for Online Course
![online](https://cloud.githubusercontent.com/assets/5269147/26276525/d15e4f3c-3d96-11e7-961a-09c71cfff851.jpg)

Image for Kids Course
![kids_course_2](https://cloud.githubusercontent.com/assets/5269147/26276529/db860806-3d96-11e7-8c82-ff2662bf51d7.jpg)

**Comment by bhavyaagg** [comment]
Please check the PR #77 . I have changed the code according to the layout.
