### ISSUE TITLE
Design a Student Testimonials page.

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#78]
We have several courses, and every course has student feedbacks. We want to fetch these feedbacks from quora/ facebook and display on our page. ( They can be fetched once using the script and hardcoded for now)

Discuss features before working on the page.
Suggesting features gets 20 Bounty Points.

**Comment by hereisnaman** [comment]
My Design has been approved by @prateek27. I am working on it.
