### ISSUE TITLE
Extra and Unusable HTML

### ISSUE THREAD

**Issue by aayusharora** [coding-blocks/coding-blocks.github.io#84]
## Steps to reproduce
- Go to [codingblocks.com](https://codingblocks.com/)
- Inspect the logo on the top left.
- You will get some other image which is `display: none` make it `display: block`.
- As the image have a transparent background, make the `background-color: black`.
![67](https://cloud.githubusercontent.com/assets/12194719/26299700/67598b92-3ef9-11e7-98b4-9250bdf83d09.png)

## Expected 
- Remove the Extra image Markup from the code.

**Comment by aayusharora** [comment]
@championswimmer Add the bounty points to this.

**Comment by bhavyaagg** [comment]
Should the FOUNDRY logo be seen?

**Comment by aayusharora** [comment]
It should be removed from the code. @bhavyaagg

**Comment by bhavyaagg** [comment]
@aayusharora done bhaiya.

**Comment by aayusharora** [comment]
Thanks @bhavyaagg .. Do claim your points. Closing this :)

**Comment by bhavyaagg** [comment]
Yes sure. Thank you.
