### ISSUE TITLE
Suggestions: Student Testimonials Page

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/coding-blocks.github.io#85]
https://github.com/coding-blocks/coding-blocks.github.io/issues/78

Sir we can use price_table block for a single review layout, with limited content including reviewer name, pic, star rating and then on hover include separate block containing the review description, as done in team section on main page, but using price_table block rather than circular images. 

After that we can filter reviews on the basis of course using portfolio filter kind of feature like: http://codepen.io/creotip/pen/dfjeF but tweaked.

**Comment by hereisnaman** [comment]
Can even integrate load more with AJAX.

**Comment by hereisnaman** [comment]
![18641312_1390886864324028_482268622_o](https://cloud.githubusercontent.com/assets/22571395/26404279/f4345fa4-40ae-11e7-81dd-1149cbd00862.jpg)

**Comment by prateek27** [comment]
Bounty Claim Accepted & Closed.
