### ISSUE TITLE
Link home slider link

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/coding-blocks.github.io#89]
Make the "Know More" button point to 
https://codingblocks.com/courses/launchpad-online.html
in the 2nd slide of main page.

![boss_fix](https://cloud.githubusercontent.com/assets/5269147/26315019/6e265e30-3f2d-11e7-8331-5056f4c271c8.png)

**Comment by hereisnaman** [comment]
done: https://github.com/coding-blocks/coding-blocks.github.io/pull/90
