### ISSUE TITLE
Bug on Firefox browser

### ISSUE THREAD

**Issue by a2batic** [coding-blocks/coding-blocks.github.io#92]
Due to a div's height, 2 of the card of home page on firefox browser is creating misalignment
![screenshot-codingblocks com 2017-05-23 14-00-13](https://cloud.githubusercontent.com/assets/12200504/26346077/af71dfaa-3fc2-11e7-8737-a943b6971def.png)
![screenshot from 2017-05-23 14-15-48](https://cloud.githubusercontent.com/assets/12200504/26346076/af597c58-3fc2-11e7-9494-12977cd1e1d0.png)

**Comment by championswimmer** [comment]
bug accepted. bounty added. anyone who wants to fix please go ahead

**Comment by Vatsalgarg1617** [comment]
@championswimmer  may I contribute in it?
