### ISSUE TITLE
Prajjwal Bhaiya and Umair bhaiya's picture is giving status 404 on team's page

### ISSUE THREAD

**Issue by bhavyaagg** [coding-blocks/coding-blocks.github.io#93]
Since the image has been removed from the img folder. It has been moved to img/original

![screenshot from 2017-05-23 14-52-10](https://cloud.githubusercontent.com/assets/20207154/26347567/9f82b34e-3fc7-11e7-9463-33c2a92034c3.png)

**Comment by prateek27** [comment]
@bhavyaagg corrected and closing this.
