### ISSUE TITLE
Bug Report - Inconsistent UI in Safari browser

### ISSUE THREAD

**Issue by anu0012** [coding-blocks/coding-blocks.github.io#96]
The UI of the home page is not the desirable one. There is an unusual gap in Safari browser. 

# What it looks like in Chrome

![screen shot 2017-05-26 at 7 50 04 pm](https://cloud.githubusercontent.com/assets/17943805/26498482/d3c6f5fc-424c-11e7-89de-cf85ef6777f7.png)

# In Safari

![screen shot 2017-05-26 at 7 50 47 pm](https://cloud.githubusercontent.com/assets/17943805/26498507/ec2ad1ea-424c-11e7-992f-37d72d3a7ae0.png)

**Comment by championswimmer** [comment]
bug accepted. bounty added for fixing it. anyone interested please go ahead
