### ISSUE TITLE
Coming-soon page 'Buttons' doesn't redirect to right page

### ISSUE THREAD

**Issue by prateekiiest** [coding-blocks/coding-blocks.github.io#98]
Fixing a Bug from #29 

Currently when clicking on Know More or Register , it directs to an algorithm page.
![screenshot 7](https://cloud.githubusercontent.com/assets/16035442/26541310/cd5a03da-4472-11e7-802b-fa7e2a2b6eee.png)

It will be great if we can work on a single button like 'See more' and go to this required page, when clicked on it
![screenshot 8](https://cloud.githubusercontent.com/assets/16035442/26541351/f64e7406-4472-11e7-850c-7308e866eb4b.png)

**Comment by prateekiiest** [comment]
So **SOLUTION**
![screenshot 9](https://cloud.githubusercontent.com/assets/16035442/26541531/a6c8d9c0-4473-11e7-9740-1cea47adc88c.png)

clicking on it will lead to appropriate course section

**Comment by prateekiiest** [comment]
Should I start working on it?
@championswimmer 
@prateek27

**Comment by omerjerk** [comment]
@prateekiiest You can start working on it for sure. :)

**Comment by prateekiiest** [comment]
I have sent a PR for this

**Comment by omerjerk** [comment]
@prateekiiest Merged. :)
